config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  self.table_name = 'messages'

  validates_presence_of :name, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    Message.create!(message_params)
    redirect_to messages_path
  end

  private
  def message_params
    params.require(:message).permit(:name, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<% @messages.each do |m| %>
  Author: <%= m.name %><br />
  <%= m.content %><br /><br />
<% end %>

<%= link_to 'New message', new_message_path %>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
  Name: <%= f.text_field :name %><br />
  Content: <%= f.text_field :content %><br />
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<h2>Hello, world!</h2>